services:
  media-server-app:
    build:
      context: .
    container_name: media-server-app
    volumes:
      - ./docker-volume/databases:/usr/app/databases
      - ./docker-volume/uploads:/usr/app/uploads
      - ./docker-volume/.env:/usr/app/.env
    tty: true
    restart: unless-stopped
    user: app
    ports:
      - 8000:3000
