// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginPage(alerts ...string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Media Server - Login Page</title><script src=\"https://unpkg.com/@tailwindcss/browser@4\"></script></head><body><style>\n\t\t\t\tbody {\n\t\t\t\t\tbackground-color: #e0f7fa;\n\t\t\t\t\tfont-family: Arial, sans-serif;\n\t\t\t\t\theight: 100dvh;\n\t\t\t\t\tmargin: 0;\n\t\t\t\t}\n\t\t\t\t.login-container {\n\t\t\t\t\tbackground-color: white;\n\t\t\t\t\tpadding: 20px;\n\t\t\t\t\tmargin: 0px 10px;\n\t\t\t\t\tborder-radius: 8px;\n\t\t\t\t\tbox-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n\t\t\t\t}\n\t\t\t\tinput[type=\"text\"], input[type=\"password\"] {\n\t\t\t\t\twidth: 100%;\n\t\t\t\t\tpadding: 10px;\n\t\t\t\t\tmargin: 10px 0;\n\t\t\t\t\tborder: 1px solid #00796b;\n\t\t\t\t\tborder-radius: 4px;\n\t\t\t\t}\n\t\t\t\tinput[type=\"submit\"] {\n\t\t\t\t\tbackground-color: #00796b;\n\t\t\t\t\tcolor: white;\n\t\t\t\t\tpadding: 10px;\n\t\t\t\t\tborder: none;\n\t\t\t\t\tborder-radius: 4px;\n\t\t\t\t\tcursor: pointer;\n\t\t\t\t\twidth: 100%;\n\t\t\t\t}\n\t\t\t\tinput[type=\"submit\"]:hover {\n\t\t\t\t\tbackground-color: #004d40;\n\t\t\t\t}\n\t\t\t</style><div class=\"login-container\"><div class=\"header-login-container\"><h2 class=\"title\">Welcome To</h2><h3 class=\"sub-title\">Media-Server</h3></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, alert := range alerts {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p style=\"color: rgb(175, 0, 0);\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(alert)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `features/views/login.templ`, Line: 54, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form method=\"post\" action=\"/\"><input id=\"username\" name=\"username\" type=\"text\" style=\"width: 95%;\" placeholder=\"Username\" required> <input id=\"password\" name=\"password\" type=\"password\" style=\"width: 95%;\" placeholder=\"Password\" required> <input type=\"submit\" value=\"Login\"></form><style>\n\t\t\t\tbody {\n\t\t\t\t\t\tdisplay: flex;\n\t\t\t\t\t\tjustify-content: center;\n\t\t\t\t\t\talign-items: center;\n\t\t\t\t}\n\t\t\t\t\n\t\t\t\t.title {\n\t\t\t\t\tcolor: #00796b;\n\t\t\t\t\twidth: 100%;\n\t\t\t\t\ttext-align: center;\n\t\t\t\t}\n\n\t\t\t\t.sub-title {\n\t\t\t\t\tcolor: #00796b;\n\t\t\t\t\twidth: 100%;\n\t\t\t\t\ttext-align: center;\n\t\t\t\t}\n\n\t\t\t\t.header-login-container {\n\t\t\t\t\tdisplay: flex;\n\t\t\t\t\tflex-direction: column;\n\t\t\t\t\tjustify-content: center;\n\t\t\t\t\talign-items: center;\n\t\t\t\t}\n\t\t\t</style></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
